### ISSUE TITLE
iOS bug with Vimeo iframe when fullscreen button pressed

### ISSUE THREAD

**Issue by SleepyNiko** [biati-digital/glightbox#103]
**Describe the bug**
When using an iOS device, and viewing a Vimeo iframe embed in glightbox, the video disappears leaving the overlay and close button. This does not happen on Android (at least in my tests so far).

**Are you able to reproduce the bug in the demo site**
Yes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on video CTA/thumbnail to bring up glightbox window (below screenshot 'step 1')
2. Click on the "Vimeo" fullscreen button once the glightbox window is open (below screenshot 'step 2')
3. Video disappears, leaving the overlay and close button visible (below screenshot 'step 3')

**Expected behaviour**
The video is expected to expand to fullscreen as seen in the Android tests.

**Screenshots**
Step 1: https://www.screencast.com/t/5mHw4BqE 
Step 2: https://www.screencast.com/t/a5mK82CQ5
Step 3: https://www.screencast.com/t/uai1OrQcF

**Smartphone:**
 - Device: iPhone8, iPhoneX, iPhone11, iPhone11pro
 - iOS (latest versions)
 - Browser [chrome, & safari]
 - Latest versions of each

**Comment by biati-digital** [comment]
Do not own an IOS device so pull requests are welcome

**Comment by biati-digital** [comment]
This should be fixed in the latest version 2.0.6

**Comment by kyledwagner** [comment]
This issue still persists in the latest update. I’m on the latest iOS 13.5. The full screen is hidden behind the website somehow and the X to close is still shown. 

Can this be fixed somehow?

**Comment by kyledwagner** [comment]
The latest 3.0.0 release still has this bug issue. Even on the home page.

**Comment by sammularczyk** [comment]
Same thing happens with the YouTube video on the homepage!

**Comment by biati-digital** [comment]
Hi, this should be fixed in the new update 3.0.2, please try it and let me know if it's working for you.
