### ISSUE TITLE
Prev/Next image by MOUSE dragging (touch work perfect!)

### ISSUE THREAD

**Issue by gitrequests** [biati-digital/glightbox#11]

**Comment by mcstudios** [comment]
I want to keep the library small, i'm open to this idea if more people want this to be implemented but for now there are no plans to integrate this feature.

**Comment by Hirbod** [comment]
Was about to implement this library but after spectating the API and examples I was disappointed that there is no mouse drag support. Sad, thats a exclusion criterion for a very good looking lightbox

**Comment by biati-digital** [comment]
Hi @Hirbod the reason this feature is not yet implemented is that GLightbox has had 75,464 downloads only on npm (not counting GitHub downloads), and you can see on this issue that not many people have requested this feature.

![Screen Shot 2020-06-11 at 8 51 08](https://user-images.githubusercontent.com/1219228/84393207-ed358680-abc0-11ea-9cf5-336c655671f8.png)

**Comment by Hirbod** [comment]
I'll drop 100 $ via PayPal if this feature gets implemented

**Comment by biati-digital** [comment]
Hi @Hirbod  Awesome, here's the link to PayPal, i can work on this feature this weekend once i receive the PayPal notification. 

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://paypal.me/bdigital9816/100usd)

**Comment by Hirbod** [comment]
I'll drop 50$ now and 50$ when its done and tested, is that a deal?

**Comment by biati-digital** [comment]
Hi @Hirbod I'm sorry, that will not work for me but i can assure you that the functionality will work correctly, once you try it you can give me your comments and let me know if something about the implementation needs to be adjusted.

**Comment by Hirbod** [comment]
Well I already give you a advantage of trust for dropping 50% of the amount now - I need something in return :)

**Comment by biati-digital** [comment]
Ok, how about this, if you pay the 100 upfront i'll include the option you want to disable zoom (This is a functionality that i don't think is necessary and has been requested less than the mouse drag feature otherwise the issue #141 will probably be tagged as feature request and hope a lot of people vote to add it) 

Or you pay 75% upfront and 25% once done. This will not include the zoom option.

Let me know what you think.

**Comment by Hirbod** [comment]
I paid the 100$. Hopefully you also fix the gallery Id issue, which is more important then the zoom thing

**Comment by biati-digital** [comment]
Thank you @Hirbod and yes the gallery issue was also planned for the next update.

**Comment by Hirbod** [comment]
Hi @biati-digital, did you manage to get it done through the weekend? :)

**Comment by biati-digital** [comment]
hi @Hirbod, Yes, i'll release an update today as soon as i finish some tests.

**Comment by biati-digital** [comment]
The update has been released, the new version 3.0.2 includes this feature, new options and bug fixes, you can find more information in the readme. For draggable there's a new global setting called  **draggable** and can also be overwritten by each specific slide using data-draggable="false" 

Please try it and let me know how it works

**Comment by Hirbod** [comment]
Hi @biati-digital I just tested out, thanks for your quick work. It works, but what I personally do dislike is the fact that it automatically snaps when the threshhold is reached. It should work with kind of velocity and should only perform the real slide when the mouse was released.

**Comment by biati-digital** [comment]
Hi @Hirbod, i do understand what you're saying, what do you think about having both behaviors? maybe have another option to enable or disable the automatic change when the threshhold is reached?

**Comment by Hirbod** [comment]
Would be lovely.

**Comment by biati-digital** [comment]
I just published an update with a new option "dragAutoSnap", more info in the README 😃

please try it and let me know what you think.

**Comment by Hirbod** [comment]
I like it much more that way now, what I am still missing is that while dragging, the next/prev slide remains invisible (while it should be dragged into viewport, too, like in the mobile touch version).

I can live with that personally, but actually I really thought that you just gonna bring the same view from mobile to desktop using drag instead of touch. U kinda reinvented the wheel :D

**Comment by biati-digital** [comment]
Actually that does not happen in the mobile version, you are not able to see the incoming slide until it's active.

This is because of the way the code was created to handle the slide effects/transitions.

But i can not deny that this is something I've been wanting to change.

**Comment by biati-digital** [comment]
Closing as this is already implemented.
