### ISSUE TITLE
Crash when opening second gallery with multiple galleries in the page

### ISSUE THREAD

**Issue by ckybonist** [biati-digital/glightbox#143]
**Describe the bug**
1. I create one `glightbox` instance and specify multiple `data-gallery` on the page.
2. Open one gallery, navigate few images, then close.
3. Open another gallery, then the glightbox will throw the error:
![image](https://user-images.githubusercontent.com/3832925/88759603-bc73d580-d19d-11ea-9412-92f67bce8878.png)

Moreover, I couldn't close the lightbox container by clicking the close button or backdrop

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
As the description.

**Expected behavior**
The Glightbox wouldn't crash when opening any gallery.

**Post the code you are using**
```js
import GLightbox from 'glightbox';
import 'glightbox/dist/css/glightbox.min.css';

const glightbox = GLightbox({
  touchNavigation: true,
  loop: false,
  width: '100%'
});
```

**Screenshots**
### Glightbox throwed the error, and container was freezing
![image](https://user-images.githubusercontent.com/3832925/88760137-f1ccf300-d19e-11ea-94b8-56e11d9dd515.png)

**Desktop:**
- OS: macOS 10.14.6
- Browser: Chrome 84, Safari 13.1.2
- glightbox Version: `> 2.0.6`

**Smartphone:**

**Comment by biati-digital** [comment]
I just published an update that should fix this error, please try it and let me know if it's working for you.

**Comment by ckybonist** [comment]
It's working! Thanks : ) @biati-digital

**Comment by smarinade** [comment]
Thanks @biati-digital, it fixed my issue.

**Comment by biati-digital** [comment]
Glad it's working, closing this now.

**Comment by nbayramberdiyev** [comment]
I still have this issue even though I'm using the latest version.

I created multiple galleries, and one GLightbox instance:

```
const lightbox = GLightbox();
```

![glightbox](https://user-images.githubusercontent.com/23094428/90319429-c557fb80-df40-11ea-9374-9e8b082816a3.PNG)

**Comment by biati-digital** [comment]
Hi @nbayramberdiyev i'm not able to replicate the error, it has been confirmed here and another issue that this has been solved. I also tried it in the demo site and i'm not able to replicate it.

Please try your code directly in the demo site, just download the latest release and try creating multiple galleries in the index.html file, if you are able to replicate the error in the demo site please share the code you are using.

**Comment by nbayramberdiyev** [comment]
Tried directly in the demo site, still get `Uncaught TypeError: Cannot read property 'create' of undefined` error. Added `data-gallery` attribute to the first two images in the demo:

```
<li class="box">
    <div class="inner">
        <a href="demo/img/large/gm1.jpg" class="glightbox" data-gallery="g1">
            <img src="demo/img/small/gm1.jpg">
        </a>
    </div>
</li>
<li class="box">
    <div class="inner">
        <a href="demo/img/large/gm2.jpg" class="glightbox" data-gallery="g2">
            <img src="demo/img/small/gm2.jpg" alt="image">
        </a>
    </div>
</li>
```
As you can see in the code, I specified `data-gallery="g1"` and `data-gallery="g2"`. Didn't change anything else. Maybe I'm doing it wrong. Let me know if I'm getting this error due to wrong configuration.

**Comment by biati-digital** [comment]
@nbayramberdiyev just tried your code in the demo site and it works, i don't get any errors and the lightbox works correctly, if you want you can set up a live example so i can take a look because i'm not able to replicate it and it has been confirmed by several people that this issue was fixed in a previous update.
