### ISSUE TITLE
openEffect / closeEffect no longer accepting "none"

### ISSUE THREAD

**Issue by marios88** [biati-digital/glightbox#150]
**Describe the bug**
openEffect / closeEffect no longer accepting "none"

**Are you able to reproduce the bug in the demo site**
https://codepen.io/marios88/pen/YzqGpyK

**To Reproduce**
1. Go to https://codepen.io/marios88/pen/YzqGpyK
2. Click on text

**Expected behavior**
Lightbox opens and shows image

**Post the code you are using**
```
const lightbox = GLightbox({
        openEffect: "none",
        closeEffect: "none"
});
```

**Screenshots**
No

**Desktop:**
 - OS: Linux
 - Browser Firefox
 - Version 79

**Comment by biati-digital** [comment]
Hi @marios88, this error has been fixed in the latest version 3.0.5

**Comment by marios88** [comment]
Sorry to bother you again but

https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js

seems to point to the previous version with the issue still active
